name: Build

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_win.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --name "Code Launcher" --windowed --icon assets\icon.ico --add-data "assets:." --clean --noconfirm .\app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: dist/*

  build-mac-m1:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --name "Code Launcher" --windowed --icon assets/icon.ico --add-data "assets:." --clean --noconfirm ./app.py
          cd dist/
          zip -r9 "Code Launcher" "Code Launcher.app/"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mac-arm
          path: dist/Code Launcher.zip
