name: Build

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements_win.txt

      - name: Install MSVC toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build with Nuitka
        run: |
          python -m nuitka app.py
          rename app.dist/app.exe "app.dist/Code Launcher.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            'app.dist/Code Launcher.exe'
            app.dist/assets

  build-mac-m1:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          python -m nuitka app.py
          ls .
          ls app.dist/
          mv app.dist/app.app 'app.dist/Code Launcher.app'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm
          path: |
            'app.dist/Code Launcher.app'
            app.dist/assets
